-- MySQL Script generated by MySQL Workbench

-- Wed May  9 19:22:29 2018

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering



SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';



-- -----------------------------------------------------

-- Schema mydb

-- -----------------------------------------------------



-- -----------------------------------------------------

-- Schema mydb

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;

USE mydb ;



-- -----------------------------------------------------

-- Table mydb.`User`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.`User` (

  User_Id INT NOT NULL,

  User_Pseudo VARCHAR(20) NOT NULL,

  User_Birthdate DATE NOT NULL,

  User_Email VARCHAR(200) NOT NULL,

  User_Gender VARCHAR(1) NOT NULL,

  PRIMARY KEY (User_Id))

ENGINE = InnoDB;





-- -----------------------------------------------------

-- Table mydb.`User`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.`User` (

  User_Id INT NOT NULL,

  User_Pseudo VARCHAR(20) NOT NULL,

  User_Birthdate DATE NOT NULL,

  User_Email VARCHAR(200) NOT NULL,

  User_Gender VARCHAR(1) NOT NULL,

  PRIMARY KEY (User_Id))

ENGINE = InnoDB;





-- -----------------------------------------------------

-- Table mydb.`Friends`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.`Friends` (

  Friends_Date DATE NULL,

  Friends_User_Id1 INT NOT NULL,

  Friends_User_Id2 INT NOT NULL,

  INDEX fk_Friends_User_idx (Friends_User_Id1 ASC),

  INDEX fk_Friends_User1_idx (Friends_User_Id2 ASC),

  PRIMARY KEY (Friends_User_Id1, Friends_User_Id2),

  CONSTRAINT fk_Friends_User

    FOREIGN KEY (Friends_User_Id1)

    REFERENCES mydb.`User` (User_Id)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION,

  CONSTRAINT fk_Friends_User1

    FOREIGN KEY (Friends_User_Id2)

    REFERENCES mydb.`User` (User_Id)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION)

ENGINE = InnoDB;





-- -----------------------------------------------------

-- Table mydb.`Publication`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.`Publication` (

  Publication_Id INT NOT NULL,

  Publication_Content VARCHAR(500) NULL,

  Publication_Date DATE NULL,

  Publication_User_Id INT NOT NULL,

  PRIMARY KEY (Publication_Id),

  INDEX fk_Publication_User1_idx (Publication_User_Id ASC),

  CONSTRAINT fk_Publication_User1

    FOREIGN KEY (Publication_User_Id)

    REFERENCES mydb.`User` (User_Id)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION)

ENGINE = InnoDB;





-- -----------------------------------------------------

-- Table mydb.`Comment`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.`Comment` (

  Comment_Id INT NOT NULL,

  Comment_Date DATE NULL,

  Comment_Content VARCHAR(200) NULL,

  Comment_User_Id INT NOT NULL,

  Comment_Publication_Id INT NOT NULL,

  PRIMARY KEY (Comment_Id),

  INDEX fk_Comment_User1_idx (Comment_User_Id ASC),

  INDEX fk_Comment_Publication1_idx (Comment_Publication_Id ASC),

  CONSTRAINT fk_Comment_User1

    FOREIGN KEY (Comment_User_Id)

    REFERENCES mydb.`User` (User_Id)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION,

  CONSTRAINT fk_Comment_Publication1

    FOREIGN KEY (Comment_Publication_Id)

    REFERENCES mydb.`Publication` (Publication_Id)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION)

ENGINE = InnoDB;





-- -----------------------------------------------------

-- Table mydb.`FriendsRequest`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.`FriendsRequest` (

  Friends_Date DATE NULL,

  Friends_User_IdRequester INT NOT NULL,

  Friends_User_IdRequestee INT NOT NULL,

  INDEX fk_Friends_User_idx (Friends_User_IdRequester ASC),

  INDEX fk_Friends_User1_idx (Friends_User_IdRequestee ASC),

  PRIMARY KEY (Friends_User_IdRequester, Friends_User_IdRequestee),

  CONSTRAINT fk_Friends_User0

    FOREIGN KEY (Friends_User_IdRequester)

    REFERENCES mydb.`User` (User_Id)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION,

  CONSTRAINT fk_Friends_User10

    FOREIGN KEY (Friends_User_IdRequestee)

    REFERENCES mydb.`User` (User_Id)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION)

ENGINE = InnoDB;





SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
